config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games do
    member do
      post 'next_player'
      post 'next_dare'
      post 'restart'
    end
  end

  resources :players

  resources :dares

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dare.rb
# frozen_string_literal: true

class Dare < ApplicationRecord
  belongs_to :user
  belongs_to :game, optional: true

  validates :template, presence: true

  def construct_dare
    return unless self.game.present? && self.template.present?

   	dare_constructor = DareConstructor.new(self.template, self.game)
   	dare_constructor.construct_dare 
  end
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user  
  has_many :players
  serialize :used_dare_ids, type: Array, coder: YAML
  after_create :set_initial_player
  after_create :select_dare

  def current_player
    Player.find_by(id: current_player_id)
  end

  def set_initial_player
    update!(current_player_id: players.first.id) if current_player_id.nil? && players.any?
  end

  def selected_dare
    Dare.find_by(id: selected_dare_id)
  end

  def select_next_player
    players_ids = players.order(:id).pluck(:id)
    return if players_ids.empty?
    
    current_index = if current_player_id.present?
                      players_ids.index(current_player_id)
                    else 
                      0
                    end
    next_index = (current_index + 1) % players_ids.count # if last ==> first 
    next_player_id = players_ids[next_index]

    update!(current_player_id: next_player_id)
  end

  def select_dare
    self.selected_dare_id = available_dares_ids.sample
    used_dare_ids.push(selected_dare_id) unless selected_dare_id.nil?
    save!
  end

  def available_dares_ids
    Dare.pluck(:id).to_a - used_dare_ids.map(&:to_i)  
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :game
  before_destroy :adjust_game_current_player

  validates :name, presence: true
  validates :gender, presence: true

  enum gender: { female: 0, male: 1 }

  private

  def adjust_game_current_player
    game.select_next_player if game.current_player_id == id
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :game, dependent: :destroy
  has_many :dares, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dares_controller.rb
class DaresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dare, only: [:edit, :update, :destroy]

  def index
    @dares = current_user.dares
  end

  def show
    @dare = Dare.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to dares_path, alert: "Dare not found."
  end

  def new
    @dare = current_user.dares.build
  end

  def edit
  end

  def create
    @dare = current_user.dares.build(dare_params)
    @dare.user = current_user
    @dare.game = current_user.game
    if @dare.save
      redirect_to @dare, notice: I18n.t('notices.dare_created')
    else
      render :new
    end
  end

  def update
    if @dare.update(dare_params)
      redirect_to @dare, notice: I18n.t('notices.dare_updated')
    else
      render :edit
    end
  end

  def destroy
    if @dare.present?
      @dare.destroy
    else
      redirect_to dares_path
    end
  end

  private

  def set_dare
    @dare = Dare.find(params[:id])
  end

  def dare_params
    params.require(:dare).permit(:template)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: %i[show edit update destroy next_player next_dare restart]

  def show
    @current_player = @game.current_player
    @selected_dare = @game.selected_dare
  end

  def new
    redirect_to current_user.game, alert: I18n.t('notices.game_already_exists') if current_user.game.present?
    @game = Game.new
  end

  def next_player
    @game.select_next_player
    @game.select_dare
    redirect_to game_path(@game)
  end

  def next_dare
    @game.select_dare
    redirect_to game_path(@game)
  end

  def restart
    @game.update!(used_dare_ids: [])
    next_dare
  end

  def edit; end

  def create
    if current_user.game.present?
      redirect_to root_path, alert: I18n.t('notices.game_already_exists')
    else
      @game = current_user.build_game(game_params)
      if @game.save
        redirect_to new_player_path(game_id: @game.id), notice: I18n.t('notices.game_created_add_player')
      else
        render :new
      end
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game, notice: I18n.t('notices.game_updated')
    else
      render :edit
    end
  end

  def destroy
    @game.destroy!
    redirect_to games_url, notice: I18n.t('notices.game_destroyed')
  end

  private

  def set_game
    @game = current_user.game
    redirect_to root_path, alert: I18n.t('notices.game_not_found') unless @game
  end

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.game
        redirect_to game_path(current_user.game)
      else
        redirect_to new_game_path
      end
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_player, only: %i[show edit update destroy]
  after_action :ensure_current_player, only: %i[create destroy]

  def index
    @players = Player.all
  end

  def show
    @players = current_user.game.players
  end

  def new
    @player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = current_user.game.players.build(player_params)
    if @player.save
      redirect_to players_url, notice: I18n.t('notices.player_created')
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: I18n.t('notices.player_updated')
    else
      render :edit
    end
  end

  def destroy
    current_user.game.select_next_player if current_user.game.current_player_id == @player.id
    @player.destroy!
    redirect_to players_url, notice: I18n.t('notices.player_destroyed')
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :gender)
  end

  def ensure_current_player
    game = current_user.game
    game.set_initial_player if game.current_player_id.nil?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('notices.user_updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to users_url, notice: I18n.t('notices.user_destroyed')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/dares/edit.html.erb
<h1>Edit Dare</h1>

<%= form_with(model: @dare, local: true) do |form| %>
  <% if @dare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dare.errors.count, "error") %> prohibited this dare from being saved:</h2>
      <ul>
        <% @dare.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :template, "Dare Template" %>
    <%= form.text_area :template, rows: 5 %>
  </div>

  <div class="actions">
    <%= form.submit "Update Dare", class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back to Dares', dares_path, class: 'btn btn-secondary' %>

app/views/dares/index.html.erb
<h1>Your Dares</h1>

<ul>
  <% @dares.each do |dare| %>
    <li>
      <%= dare.template %>
      <%= link_to 'Edit', edit_dare_path(dare), class: 'btn btn-warning' %>
      <%= button_to 'Delete', dare_path(dare), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </li>
  <% end %>
</ul>

<%= button_to 'Add Dare', new_dare_path, method: :get, class: 'btn btn-primary' %>
<%= button_to 'Go to Game', game_path(current_user.game), method: :get, class: 'btn btn-success' %>

app/views/dares/new.html.erb
<h1>Create a New Dare</h1>

<%= form_with(model: @dare, local: true) do |form| %>
  <% if @dare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dare.errors.count, "error") %> prohibited this dare from being saved:</h2>
      <ul>
        <% @dare.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :template, "Dare Template" %>
    <%= form.text_area :template, rows: 5 %>
  </div>

  <div class="actions">
    <%= form.submit "Create Dare", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dares/show.html.erb
<h1>Dare Details</h1>

<p>
  <strong>Template:</strong>
  <%= @dare.template %>
</p>

<%= link_to 'Edit', edit_dare_path(@dare), class: 'btn btn-warning' %>
<%= link_to 'Back to Dares', dares_path, class: 'btn btn-secondary' %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Game</title>
</head>
<body>
  <h1>Edit Game</h1>
  <%= render 'form', game: @game %>
</body>
</html>

app/views/games/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Game</title>
</head>
<body>
  <h1>New Game</h1>
  <%= render 'form', game: @game %>
</body>
</html>

app/views/games/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game Dare</title>
</head>
<body>
  <h1>Game Dare</h1>
  <p><%= @current_player&.name %> - <%= @selected_dare.construct_dare unless @selected_dare == nil %></p>
  <%= button_to "Next", next_player_game_path(@game), method: :post %>
  <%= button_to "Refresh", next_dare_game_path(@game), method: :post %>
  <%= button_to "Restart", restart_game_path(@game), method: :post %>
  <%= button_to 'Players', players_path, method: :get, class: 'btn btn-primary' %>
  <%= button_to 'Dares', dares_path, method: :get, class: 'btn btn-primary' %>
</body>
</html>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DareOrDare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name do %>
      Name <span class="required">*</span>
    <% end %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender do %>
      Gender <span class="required">*</span>
    <% end %>
    <%= form.collection_select :gender, Player.genders.keys, :to_s, :humanize, prompt: 'Select Gender' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/destroy.html.erb
<%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/players/edit.html.erb
<h1>Edit Player</h1>
<%= render 'form' %>

app/views/players/index.html.erb
<h1>All Players</h1>

<% if current_user.game.present? %>
  <ul>
    <% @players.each do |player| %>
      <li>
        <%= "#{player.name} #{player.gender}" %>
        <%= button_to 'Delete', player_path(player), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </li>
    <% end %>
  </ul>
  <%= button_to 'Add Player', new_player_path, method: :get, class: 'btn btn-primary' %>
  <%= button_to 'Go to Game', game_path(current_user.game), method: :get, class: 'btn btn-success' %>
<% else %>
  <p>You do not have an active game. Please create a game to start adding players.</p>
  <%= button_to 'Create Game', new_game_path, method: :get, class: 'btn btn-primary' %>
<% end %>

app/views/players/new.html.erb
<h1>New Player</h1>
<%= render 'form', player: Player.new %>

app/views/players/show.html.erb
<h1>Player Details</h1>
<p><strong>Name:</strong> <%= @player.name %></p>
<p><strong>Gender:</strong> <%= @player.gender %></p>
<%= button_to 'Add Player', new_player_path, method: :get, class: 'btn btn-primary' %>
<%= button_to 'Go to Game', game_path(current_user.game), method: :get, class: 'btn btn-success' %>